<template>
  <div>
    <b-container>
      <b-row align-h="center">
        <b-row>
          <b-col cols="2">
            <b-img :src="logo" fluid alt="Edtech Logo"></b-img>
          </b-col>
          <b-col cols="10"></b-col>
        </b-row>
        <b-col cols="8">
          <h1 class="my-2">{{this.reportData.name}}Report</h1>
          <p>
            Generated by: {{this.reportData.author}}
            <br />
            Created on {{getTime(this.reportData.dateCreated)}}
          </p>

          <div
            v-for="(section, sectionIndex) in this.sections"
            v-bind:key="section.id"
            class="mt-3"
          >
            <h3>Section {{sectionIndex+1}} {{section.name}}</h3>

            <div v-for="(a, index) in section.question" v-bind:key="index" class="text-left mb-3">
              <div>
                <h5 class="d-inline font-weight-bold">{{a.questionName}}:</h5>
                <p class="d-inline mb-2">{{a.descriptions[a.selected]}}</p>
              </div>
              <div class="font-italic">
                <h6>Comment:</h6>
                <p>{{a.comment}}</p>
              </div>
            </div>
          </div>

          <div class="mt-5 text-center">
            <label for="textarea">Recommendation:</label>
            <b-form-textarea
              id="textarea"
              v-model="recommendation"
              placeholder="Write your recommendation here"
              rows="5"
              max-rows="6"
            ></b-form-textarea>
          </div>

          <div>
            <div class="mt-3">
              <b-button-group>
                <b-button variant="outline-primary" @click="save">Save</b-button>
                <b-button variant="outline-primary">Download Report</b-button>
                <b-button variant="outline-primary">Back</b-button>
              </b-button-group>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
import logo from "@/assets/Logo.png";
import { updateDocument } from "@/tools/firebaseTool";
import * as firebase from "firebase";
import { db } from "@/tools/firebaseConfig";

export default {
  name: "Report_preview",
  data() {
    return {
      logo: logo,
      report: {},
      reportData: {},
      sections: [],
      recommendation: "",
    };
  },
  methods: {
    save() {
      console.log(this.report.id);
      updateDocument("report", this.report.id, {
        recommendation: this.recommendation,
        isCompleted: true,
        dateEdited: firebase.firestore.Timestamp.fromDate(new Date()),
      });
      window.alert("Successfully uploaded");
    },
    getTime: function (rawDate) {
      if (rawDate) {
        let m = new Date(rawDate.seconds * 1000);
        return m.toLocaleString();
      }
    },
  },
  created: async function () {
    let report_ref = db.collection("report").doc(this.$route.params.reportId);
    this.report = await report_ref.get();
    this.reportData = this.report.data();

    for (let sectionRef of this.reportData.content) {
      let sectionPath = sectionRef.path;
      let section = await db.doc(sectionPath).get();
      this.sections.push(section.data());
    }
    this.recommendation = this.reportData.recommendation;
    console.log(this.sections);
  },
};
</script>

<style scoped>
* {
  color: #000;
  margin: 0;
}
</style>